### PR TITLE
Update miniz.h

### LINKED ISSUE #97: miniz.h bugfix
miniz currently does not support x86 compilers that disallow unaligned loads and stores. As a result, neither does this wonderful library :). I've opened a pull request (richgel999/miniz#124) to fix the missing guard upstream. Since you have a modified copy of miniz.h, I'm going to open a pull request to add that fix to your version as well.

### PR DESCRIPTION
**Pull request by Cgettys**
Implements upstream fix to richgel999/miniz#124 & closes #97.

### CODE REVIEW

**Comment by kuba--** [comment]
Thanks

**Comment by Cgettys** [comment]
Thanks for the handy library & the quick response! And it's the least I can do, I was using the excellent assimp library which depends on this project and we came across this issue. We figured we might as well upstream the fix so everyone can benefit :)

**Comment by Cgettys** [comment]
It also uses zlib in some places apparently, but for instance:
[D3MFExporter.cpp](https://github.com/assimp/assimp/blob/master/code/D3MFExporter.cpp). I hadn't used it personally - though the project I've been using assimp for also uses zlib in a pretty atrocious way, so I may swap over to it ;).

**Comment by sukhchainn** [comment]
I didn't know about assimp but because of you guys now I know.

Also I going to make a GUI for zip using zip and Allegro5.
It's going to be just a simple zip manipulation program with modern GUI.

**Comment by kuba--** [comment]
Thanks, it's very supportive!

**Pull request merged**
