### PR TITLE
Check __STDC_LIB_EXT1__

### PR DESCRIPTION
**Pull request by kuba--**
Closes https://github.com/kuba--/zip/issues/56

@drizt - could you check if it works or you?

### CODE REVIEW

**Comment by drizt** [comment]
Now I can compile with MinGW 4.8.2 and MinGW 4.9.2. But anyway code looks incorrect. I think it should be such

```
#ifdef __STDC_LIB_EXT1__
  if (!localtime_s(&t, tm)) {
    goto cleanup;
  }
#elif defined(_MSC_VER) || defined(__MINGW32__)
  if (localtime_s(tm, &t)) {
    goto cleanup;
  }
#else
  tm = localtime(&t);
#endif
```

WinAPI/MSVC `localtime_s` version [declared](https://msdn.microsoft.com/en-us/library/a442x3ye.aspx) as:

    errno_t localtime_s(struct tm* _tm, const time_t *time);  

c11 standard `localtime_s` version [declared](https://en.cppreference.com/w/c/chrono/localtime) as:

    struct tm *localtime_s(const time_t *restrict time, struct tm *restrict result);

**Comment by drizt** [comment]
Hard to say. It fully works in MinGW 5.3.0. But in 4.8.2 and 4.9.2 there is linking error. Actually how I mention before `errno_t localtime_s(struct tm* _tm, const time_t *time); ` is exists in MinGW 4.8.2 but need to find a way to enable it. Also in MinGW `__STDC_LIB_EXT1__` has no effect.

**Comment by kuba--** [comment]
so maybe we should go with:
```
#ifdef __STDC_LIB_EXT1__
  if (!localtime_s(&t, tm)) {
    goto cleanup;
  }
#else
  tm = localtime(&t);
#endif
```

by ignoring non standard api

**Comment by kuba--** [comment]
I just decided to use `_s` version when `__STDC_LIB_EXT1__` is defined

**Comment by drizt** [comment]
Ok. No problem. Thanks.

**Pull request merged**
