### PR TITLE
forward changes we use in ogre

### PR DESCRIPTION
**Pull request by paroj**

### CODE REVIEW

**Review by kuba-- — COMMENTED** [review]
`zip_entry_open(struct zip_t *zip, const char *entryname, int case_sensitive)`
breaks API backward compatibility.

I suggest to rename the function to something like `zip_entry_opencasesensitive`

**Comment by paroj** [comment]
added overload for API compatibility

**Review by kuba-- — CHANGES_REQUESTED** [review]
- Header file does not export `zip_entry_open` (but `zip_entry_open2`) what also breaks backward compatibility.
- I think we can do better with naming (be more descriptive instead of `zip_entry_open2`.
- The PR does not compile.
- No tests

**Comment by paroj** [comment]
> Header file does not export zip_entry_open (but zip_entry_open2) what also breaks backward compatibility.

inline methods are not part of the export interface. The change is API compatible, but not ABI compatible

> I think we can do better with naming (be more descriptive instead of zip_entry_open2

following what miniz does here. Putting "case_sensitive" into the function name kind of defies the purpose of having a parameter. Commited an alternative API for this.

**Review by kuba-- — APPROVED** [review]

**Pull request merged**
