### PR TITLE
chmod 666 to delete the test file on windows

### PR DESCRIPTION
**Pull request by kuba--**
Fixes https://github.com/kuba--/zip/issues/59

@drizt - Please take a look if it works with MSYS2 on windows

### CODE REVIEW

**Comment by drizt** [comment]
Will do.

**Comment by drizt** [comment]
The same.

**Comment by drizt** [comment]
With 06dd20a

```
ivan@winlix MSYS ~/dev/zip/aaa
$ ./test/test.exe.exe

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
[0]: test/test-1.txt
[1]: test/test-2.txt
[2]: test/empty/ (DIR)
[3]: empty/ (DIR)
100777 != 100666
Assertion failed!

Program: C:\msys64\home\ivan\dev\zip\aaa\test\test.exe.exe
File: ../test/test.c, Line 338

Expression: XMODE == file_stats.st_mode
```

**Comment by kuba--** [comment]
It's kind of broken on mingw, but it's related to windows. 
> Unlike POSIX, MS-Windows doesn't use mode flags to mark a file as executable, so there is no way 'chmod -x' can ever do anything useful on the MSYS platform

**Comment by kuba--** [comment]
I'm ignoring this test on windows

**Comment by drizt** [comment]
suddenly :)

**Comment by kuba--** [comment]
I can add smaller one just with read permissions, because on windows it we have attributes for that.

**Pull request merged**
