### PR TITLE
add odin binding link

### PR DESCRIPTION
**Pull request by thechampagne**

### CODE REVIEW

**Comment by kuba--** [comment]
If you have just one binding, why not to put the link next to the `Odin` snippet as (with note: third party implementation)

**Comment by thechampagne** [comment]
I wrote more after I opened the pull request.

**Comment by kuba--** [comment]
If you have more than 3 we can think about special table/section. Right now, I think it makes sense to add an extra link per snippet.

**Comment by thechampagne** [comment]
Should I change the snippet to use the binding instead of manually writing C functions ?

**Comment by kuba--** [comment]
> Should I change the snippet to use the binding instead of manually writing C functions ?

It's up to you, but IMO it makes sense to just keep snippets and/or links close to each other (for consistency)

**Pull request merged**
