### PR TITLE
use size_t if it's possible

### PR DESCRIPTION
**Pull request by kuba--**

### CODE REVIEW

**Comment by kuba--** [comment]
Fixes: https://github.com/kuba--/zip/issues/195

**Comment by UAchar** [comment]
Hi,

Thanks for the changes. The number of warnings have reduced considerably.
I still get some size conversion warnings from zip.c at line 446 & 650 (please see the picture).
There are some warnings for file open/reopen ( to use _wfopen_s instead of  _wfopen) functions as well.
image
image


Thanks,
Usha

**Comment by kuba--** [comment]
`wfopen` in miniz can be tricky (especially for MSVC and different versions of MinGW), so I would leave it how it is, so far.
But I'll take a look into conversion leftovers in `zip.c`

**Comment by kuba--** [comment]
...added minor improvements.

**Comment by UAchar** [comment]
similar warnings for variable "length" in line 525/528 and 533 in zip.c.
Also, Can a Changelog file be added? right now, I have to go through the commit history here to see the previous changes.
It would be nice to have a changelog to keep up with the version history.

**Comment by kuba--** [comment]
...should be fixed, now.
Changelog is attached to every release notes.

**Pull request merged**
