### PR TITLE
undefined reference to _ftelli64 - MINGW

### PR DESCRIPTION
**Pull request by kuba--**
Fixes https://github.com/kuba--/zip/issues/193

### CODE REVIEW

**Comment by aicarambazigalo** [comment]
in my case only this is needed on top of your PR for it to work:
```patch
diff --git a/E:/Downloads/miniz.h b/vendor/kuba-zip/miniz.h
index 7148d33..96536a2 100644
--- a/E:/Downloads/miniz.h
+++ b/vendor/kuba-zip/miniz.h
@@ -4874,8 +4874,12 @@ static int mz_mkdir(const char *pDirname) {
 #define MZ_FCLOSE fclose
 #define MZ_FREAD fread
 #define MZ_FWRITE fwrite
-#define MZ_FTELL64 _ftelli64
-#define MZ_FSEEK64 _fseeki64
+
+//#define MZ_FTELL64 _ftelli64
+//#define MZ_FSEEK64 _fseeki64
+#define MZ_FTELL64 ftell
+#define MZ_FSEEK64 fseek
+
 #define MZ_FILE_STAT_STRUCT _stat64
 #define MZ_FILE_STAT mz_stat
 #define MZ_FFLUSH fflush
```

detailed context here: https://github.com/kuba--/zip/issues/193#issuecomment-909756330

**Comment by kuba--** [comment]
@aicarambazigalo - as far as I know you use MinGW, but the block which you suggested to change is the one for MSC.
So how it's possible that your MinGW does not define `__MINGW32__`?
Anyway, I've changed the condition and from `#if __MINGW32__` to `#if __MINGW64__`, hopefully it will work for you (PTAL the PR again), but frankly I don't want to change the block for MSC (`_ftelli64` should be used on MSC).

**Comment by aicarambazigalo** [comment]
> 
> 
> @aicarambazigalo - as far as I know you use MinGW, but the block which you suggested to change is the one for MSC.
> So how it's possible that your MinGW does not define `__MINGW32__`?
> Anyway, I've changed the condition and from `#if __MINGW32__` to `#if __MINGW64__`, hopefully it will work for you (PTAL the PR again), but frankly I don't want to change the block for MSC (`_ftelli64` should be used on MSC).

I'm not really sure what's being used behind the scenes by that `zig build`, I'd say it's using `zig` but maybe something else is happening behind the scenes with `zig` and `ndk`... I think maybe you could ask/wait for the person who originally made issue https://github.com/kuba--/zip/issues/193 as whatever I'm doing may not be relevant and it's possibly only confusing the issue...

I'll retry the PR and edit this comment with result though, in a sec...

**Comment by kuba--** [comment]
@aicarambazigalo - In the issue it says:
> Legacy WINDOWS does not implement _ftelli64 till msvcr80...

so definitively someone tried MSC.

**Comment by kuba--** [comment]
@aicarambazigalo - Ok, I think I know what could happen. Anyway send another update of the fix.
IMO - it should work for you on MinGW

**Comment by aicarambazigalo** [comment]
Ok so to be clear on my side, I don't have _MSC_VER defined but I do have __MINGW32__ and __MINGW64__, the reason my patch worked for me is because that if contained an OR between _MSC_VER and __MINGW64__

**Comment by aicarambazigalo** [comment]
How about something like this, as it works for me and it doesn't change those for msvc:
> but frankly I don't want to change the block for MSC (_ftelli64 should be used on MSC).

```diff
diff --git a/E:/Downloads/oldnondad/miniz.h b/vendor/kuba-zip/miniz.h
index 7148d33..36b210f 100644
--- a/E:/Downloads/oldnondad/miniz.h
+++ b/vendor/kuba-zip/miniz.h
@@ -4874,8 +4874,13 @@ static int mz_mkdir(const char *pDirname) {
 #define MZ_FCLOSE fclose
 #define MZ_FREAD fread
 #define MZ_FWRITE fwrite
+#if defined(__MINGW64__)
+#define MZ_FTELL64 ftell
+#define MZ_FSEEK64 fseek
+#else //_MSC_VER
 #define MZ_FTELL64 _ftelli64
 #define MZ_FSEEK64 _fseeki64
+#endif
 #define MZ_FILE_STAT_STRUCT _stat64
 #define MZ_FILE_STAT mz_stat
 #define MZ_FFLUSH fflush
```

**Comment by aicarambazigalo** [comment]
Let me know when oyu want me to test the PR, as I see no point in doing so right now while those two tests are failing ...

**Comment by kuba--** [comment]
Yeah, something is messed up with those defines.
Gonna close this one and start over tonight.

**Comment by kuba--** [comment]
Ok, I've fixe my PR: https://github.com/kuba--/zip/pull/208
Can you check if it works for you

**Pull request closed without merging**
